### ISSUE TITLE
Cursor in insert mode

### ISSUE THREAD

**Issue by TheTomster** [TheTomster/lwe#9]
Right now the cursor goes wherever it wants, because we don't use it for navigation. But in insert mode it's confusing to not have an indication of where you are entering text.

**Comment by gregmojonnier** [comment]
I believe my most recent change adds this functionality for the most part. It appeared to work for me when inserting/appending at the start of a line & end of a line, inserting/appending in the middle of a line, inserting at the start of a line and tabbing, inserting/appending on an indented line, inserting/appending anywhere and entering a new line then tabbing. The one case where I still have an issue is when tabbing in the middle of a line and there are 1 or more tabs that has an offset that's not evenly divisible by TABSIZE, which indicates that they are not taking up the full TABSIZE of spaces. In order to correct this case I think I will have to determine how many spaces each tab is actually using up to the cursor? I'll try to fix this case and will repost.

**Comment by TheTomster** [comment]
I wonder if the tab takes up space until the next tabstop. So if TABSIZE is 8 there would be stops at 8, 16, 24, etc... and a tab would fill in up to the next stop. So with no spaces a tab would take TABSIZE, but with 3 spaces it would take (TABSIZE - 3) in order to reach the next stop.
